// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldjS3rEw-CqHF-wJdi5URuad_HtjMyAk',
    appId: '1:786696037162:web:5cf1cffd3c978d3e57b453',
    messagingSenderId: '786696037162',
    projectId: 'flutter-app-2a473',
    authDomain: 'flutter-app-2a473.firebaseapp.com',
    storageBucket: 'flutter-app-2a473.appspot.com',
    measurementId: 'G-4T6P2RRMT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVoEpCbwmMo17qvVbAcxY30DSFYbsFog',
    appId: '1:786696037162:android:d0692425c902c2af57b453',
    messagingSenderId: '786696037162',
    projectId: 'flutter-app-2a473',
    storageBucket: 'flutter-app-2a473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxKMEVAXByGZiWsIErn2qwJzXJhXZ45g',
    appId: '1:786696037162:ios:4dedea48b5487ef657b453',
    messagingSenderId: '786696037162',
    projectId: 'flutter-app-2a473',
    storageBucket: 'flutter-app-2a473.appspot.com',
    iosClientId: '786696037162-dsfqoaj0kdhjpelntkirlcl2g4b2oshp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxKMEVAXByGZiWsIErn2qwJzXJhXZ45g',
    appId: '1:786696037162:ios:4dedea48b5487ef657b453',
    messagingSenderId: '786696037162',
    projectId: 'flutter-app-2a473',
    storageBucket: 'flutter-app-2a473.appspot.com',
    iosClientId: '786696037162-dsfqoaj0kdhjpelntkirlcl2g4b2oshp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
